version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: cd ./docker && docker build --build-arg USER=$(whoami) -t rubuschl/zephyr-riscv-hifive1:123 .
